##=====================================================
mule:
  env: "dev"
  port: "8080"
  host: "0.0.0.0"
  
##================= HTTP HTTPS ====================================  

http:
 port: "8081"
 host: "0.0.0.0"
 private:
  port: "8091"
  
https:
 port: "8083"
 private:
  port: "8093"
  
  
##=========== HTTP SYSTEM ==============================
system:
  host: "z-cloudhub-sys-app.us-e2.cloudhub.io"
  port: "80"
  basePath: "api"
  client_id: "933c6e693e7447b4b5a9ca7cd9953812"
  client_secret: "81Aa668fF3F74d6Fad7c154189B3E20c"
  
##============ JSON LOGGER =============================
json:
 logger:
  application:
   name: "learning app"
   version: "1.0.0"
##=====================================================